package com.ushareit.engine;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.ushareit.engine.datax.Job;
import com.ushareit.engine.datax.adapter.DataxAdapter;

import java.util.Map;

public class DataxExample {

    public static Context initContext(){
        Context context = new Context();
//        context.setRuntimeConfigStr("{\"sourceRegion\":\"ue1\",\"executeMode\":\"local\",\"sourceId\":\"4e84c531-7d9d-4865-83d6-4e96be38af84\",\"destinationId\":\"dfe60cd6-2690-4ab7-8f27-16c70e1b16ee\",\"catalog\":{\"table_type\":\"single\",\"sourceDb\":\"score\",\"targetDb\":\"default\",\"tables\":[{\"sourceTable\":\"engine\",\"partitions\":\"\",\"targetTable\":\"engine_t\",\"targetTablePart\":\"\",\"primaryKey\":\"\",\"addColumns\":[],\"columns\":[{\"columnType\":\"STRING\",\"name\":\"engine_key\",\"data_type\":\"varchar\",\"columnComment\":\"这个是\\\"name\\\"\",\"comment\":\"这个是\\\"name\\\"\",\"columnName\":\"name\"},{\"columnType\":\"INT\",\"name\":\"id\",\"data_type\":\"int\",\"columnComment\":\"\",\"comment\":\"\",\"columnName\":\"id\"}],\"existTargetTable\":false}],\"sync_mode\":\"full_refresh\"},\"advancedParameters\":{\"maxActiveRuns\":1,\"acrossCloud\":\"common\",\"resourceLevel\":\"standard\",\"startDate\":\"\",\"endDate\":\"\",\"dsGroups\":[],\"lifecycle\":\"Ec2spot\",\"executionTimeout\":0,\"retries\":1,\"owner\":\"\",\"collaborators\":[]},\"alertModel\":{\"success\":{\"notifyCollaborator\":false,\"alertType\":[]},\"failure\":{\"notifyCollaborator\":false,\"alertType\":[\"dingTalk\"],\"isChecked\":true},\"start\":{\"notifyCollaborator\":false,\"alertType\":[]},\"retry\":{\"notifyCollaborator\":false,\"alertType\":[]}},\"cost\":[{\"value\":100,\"key\":54}]}");
//        context.setSourceType("Mysql");
//        context.setSourceConfigStr("{\"jdbc_url_params\":\"useUnicode=true&characterEncoding=UTF-8&useSSL=false\",\"password\":\"DRQ9wk8VJ&J4eYgb\",\"database\":\"query_editor\",\"port\":3306,\"replication_method\":\"STANDARD\",\"host\":\"test.datacake-cloud.bdp.sg2.mysql\",\"ssl\":false,\"tunnel_method\":{\"tunnel_method\":\"NO_TUNNEL\"},\"username\":\"query_editor\"}");
//        context.setSinkType("Mysql");
//        context.setSinkConfigStr("{\"jdbc_url_params\":\"useUnicode=true&characterEncoding=UTF-8&useSSL=false\",\"password\":\"DRQ9wk8VJ&J4eYgb\",\"database\":\"query_editor\",\"port\":3306,\"replication_method\":\"STANDARD\",\"host\":\"test.datacake-cloud.bdp.sg2.mysql\",\"ssl\":false,\"tunnel_method\":{\"tunnel_method\":\"NO_TUNNEL\"},\"username\":\"query_editor\"}");
//        context.setRuntimeConfigStr("{\"isNewFormat\":true,\"sourceRegion\":\"ue1\",\"executeMode\":\"local\",\"sourceType\":\"mysql\",\"sourceId\":\"17\",\"destinationType\":\"iceberg\",\"destinationId\":63,\"taskParam\":{\"bandwidth\":0,\"tableLevel\":\"1级\",\"flushInterval\":0,\"tableComment\":\"\",\"batchSize\":0,\"maxBatchRows\":0},\"catalog\":{\"table_type\":\"single\",\"sync_mode\":1,\"sourceDb\":\"postgres\",\"targetDb\":\"demo\",\"tables\":[{\"autoCreateTable\":true,\"sourceTable\":\"hg_connections\",\"targetTable\":\"hg_connections_starrocks\",\"targetTablePart\":\"\",\"existTargetTable\":false,\"filterStr\":\"\",\"splitPk\":\"\",\"columns\":[{\"name\":\"fe_id\",\"data_type\":\"int\",\"comment\":\"\",\"isPK\":false,\"columnName\":\"fe_id\",\"columnType\":\"int\",\"columnComment\":\"\",\"securityLevel\":\"1级\"},{\"name\":\"used_connections\",\"data_type\":\"int\",\"comment\":\"\",\"isPK\":false,\"columnName\":\"used_connections\",\"columnType\":\"int\",\"columnComment\":\"\",\"securityLevel\":\"1级\"},{\"name\":\"max_connections\",\"data_type\":\"varchar(255)\",\"comment\":\"\",\"isPK\":false,\"columnName\":\"max_connections\",\"columnType\":\"varchar(255)\",\"columnComment\":\"\",\"securityLevel\":\"1级\"}],\"primaryKey\":\"\",\"addColumns\":[]}]},\"advancedParameters\":{\"alertModel\":{\"failure\":{\"alertType\":[],\"notifyCollaborator\":false},\"success\":{\"alertType\":[],\"notifyCollaborator\":false},\"start\":{\"alertType\":[],\"notifyCollaborator\":false},\"retry\":{\"alertType\":[],\"notifyCollaborator\":false}},\"regularAlert\":{\"notifyCollaborator\":false,\"triggerCondition\":\"notStart\",\"alertType\":[],\"offset\":0,\"checkTime\":\"0:0\",\"graularity\":\"daily\",\"isChecked\":false},\"mysqlCdcType\":\"init\",\"owner\":\"luhongyu\",\"collaborators\":[\"zhangfeng\"],\"dsGroups\":[],\"group\":\"\",\"resourceLevel\":\"standard\",\"executionTimeout\":0,\"retries\":1,\"maxActiveRuns\":1,\"emails\":\"\",\"clusterSla\":\"normal\",\"acrossCloud\":\"common\",\"startDate\":\"\",\"endDate\":\"\",\"batchParams\":\"\",\"lifecycle\":\"Ec2spot\",\"location\":\"\",\"source\":\"task\"},\"alertModel\":{\"failure\":{\"alertType\":[],\"notifyCollaborator\":false},\"success\":{\"alertType\":[],\"notifyCollaborator\":false},\"start\":{\"alertType\":[],\"notifyCollaborator\":false},\"retry\":{\"alertType\":[],\"notifyCollaborator\":false}},\"cost\":[{\"currentGroup\":0,\"value\":100,\"key\":\"54\"}]}");
        context.setRuntimeConfigStr("{\"isNewFormat\":true,\"sourceRegion\":\"ue1\",\"executeMode\":\"local\",\"sourceType\":\"mysql\",\"sourceId\":\"42\",\"destinationType\":\"iceberg\",\"destinationId\":63,\"taskParam\":{\"bandwidth\":0,\"tableLevel\":\"1级\",\"flushInterval\":0,\"tableComment\":\"\",\"location\":\"s3://cbs.flink.us-east-1/default/datacake_datastudio_school_dt/dt={{ yesterday_ds }}#year=2023\",\"batchSize\":0,\"maxBatchRows\":0},\"catalog\":{\"table_type\":\"single\",\"sync_mode\":1,\"sourceDb\":\"ds_task\",\"targetDb\":\"postgres\",\"tables\":[{\"autoCreateTable\":true,\"sourceTable\":\"student\",\"partitions\":\"dt={{ yesterday_ds }}#year=2023\",\"targetTable\":\"hg_connections\",\"targetTablePart\":\"\",\"existTargetTable\":false,\"filterStr\":\"\",\"splitPk\":\"\",\"columns\":[{\"name\":\"age\",\"data_type\":\"int\",\"comment\":\"null\",\"isPK\":false,\"columnName\":\"fe_id\",\"columnType\":\"int\",\"columnComment\":\"null\",\"securityLevel\":\"1级\"},{\"name\":\"score\",\"data_type\":\"int\",\"comment\":\"null\",\"isPK\":false,\"columnName\":\"used_connections\",\"columnType\":\"int\",\"columnComment\":\"null\",\"securityLevel\":\"1级\"}],\"primaryKey\":\"id\",\"addColumns\":[]}]},\"advancedParameters\":{\"alertModel\":{\"failure\":{\"alertType\":[],\"notifyCollaborator\":false},\"success\":{\"alertType\":[],\"notifyCollaborator\":false},\"start\":{\"alertType\":[],\"notifyCollaborator\":false},\"retry\":{\"alertType\":[],\"notifyCollaborator\":false}},\"regularAlert\":{\"notifyCollaborator\":false,\"triggerCondition\":\"notStart\",\"alertType\":[],\"offset\":0,\"checkTime\":\"0:0\",\"graularity\":\"daily\",\"isChecked\":false},\"mysqlCdcType\":\"init\",\"owner\":\"luhongyu\",\"collaborators\":[\"zhangfeng\"],\"dsGroups\":[],\"group\":\"\",\"resourceLevel\":\"standard\",\"executionTimeout\":0,\"retries\":1,\"maxActiveRuns\":1,\"emails\":\"\",\"clusterSla\":\"normal\",\"acrossCloud\":\"common\",\"startDate\":\"\",\"endDate\":\"\",\"batchParams\":\"\",\"lifecycle\":\"Ec2spot\",\"location\":\"\",\"source\":\"task\"},\"alertModel\":{\"failure\":{\"alertType\":[],\"notifyCollaborator\":false},\"success\":{\"alertType\":[],\"notifyCollaborator\":false},\"start\":{\"alertType\":[],\"notifyCollaborator\":false},\"retry\":{\"alertType\":[],\"notifyCollaborator\":false}},\"cost\":[{\"currentGroup\":0,\"value\":100,\"key\":\"54\"}]}");
        context.setSinkType("Hologres");
        context.setSinkConfigStr("{\"password\":\"XaPe4vLE2GsTJ6WqZlzpLw23sFSW6f\",\"database\":\"postgres\",\"port\":80,\"schemas\":[\"hologres\"],\"replication_method\":{\"method\":\"Standard\"},\"host\":\"hgpostcn-cn-jia3ntkff0f5-cn-beijing.hologres.aliyuncs.com\",\"ssl\":false,\"tunnel_method\":{\"tunnel_method\":\"NO_TUNNEL\"},\"username\":\"LTAI5tD5KhrDtouufFWenfVv\"}");
        context.setSourceConfigStr("{\"jdbc_url_params\":\"useSSL=false\",\"password\":\"PPwTu1zrMgWzZQ&*\",\"database\":\"ds_task\",\"port\":3306,\"replication_method\":\"STANDARD\",\"host\":\"test.datacake-cloud.bdp.sg2.mysql\",\"ssl\":false,\"tunnel_method\":{\"tunnel_method\":\"NO_TUNNEL\"},\"username\":\"ds-task\"}");
        context.setSourceType("Mysql");
        //        context.setSourceType("Starrocks");
//        context.setSinkConfigStr("{\"password\":\"123456\",\"database\":\"demo\",\"queryport\":9030,\"httpport\":8030,\"host\":\"10.32.13.109\",\"username\":\"root\"}");

        return context;
    }

    public static void main(String[] args) {
//        String json = "{\"job\":{\"content\":[{\"reader\":{\"parameter\":{\"fieldDelimiter\":\"\\t\",\"defaultFS\":\"hdfs://ip-172-17-53-122.ec2.internal:8020\",\"fileType\":\"orc\",\"path\":\"/lakehouse/warehouse/company\",\"encoding\":null,\"column\":[{\"index\":0,\"type\":\"Long\"},{\"index\":1,\"type\":\"String\"},{\"index\":2,\"type\":\"Long\"}],\"hadoopConfig\":{\"dfs.data.transfer.protection\":\"authentication\",\"dfs.client.use.datanode.hostname\":true},\"haveKerberos\":true,\"kerberosKeytabFilePath\":\"/etc/security/keytab/hive.keytab\",\"kerberosPrincipal\":\"hive/ip-172-17-53-122.ec2.internal@EXAMPLE.COM\"},\"name\":\"hdfsreader\"},\"writer\":{\"parameter\":{\"loadUrl\":[\"10.32.13.109:8030\"],\"username\":\"root\",\"password\":\"123456\",\"column\":[\"id\",\"name\",\"age\"],\"session\":null,\"preSql\":[\"select 2\"],\"postSql\":null,\"flushInterval\":0,\"loadProps\":null,\"connection\":[{\"table\":[\"company2_pt\"],\"selectedDatabase\":\"demo\",\"jdbcUrl\":\"jdbc:mysql://10.32.13.109:9030/demo\"}]},\"name\":\"doriswriter\"},\"transformer\":[]}],\"setting\":{\"jvm\":\"-Xms2G -Xmx2G\",\"speed\":{\"channel\":2}}}}";
//        JSONObject jobJson = JSON.parseObject(json);
//        Job job = JSON.parseObject(jobJson.getString("job"), Job.class);
//        Map<String, Object> setting = job.getSetting();
//        String jvm = (String) setting.getOrDefault("jvm", "-Xms1G -Xmx1G");
//        System.out.println(jvm);
//        System.out.println(setting);
        Context context=initContext();
        String jobInfo=DataxAdapter.getJobInfo(context);
        System.out.println(jobInfo);
    }
}
