system:
  code: dataStudio

zeus:
  login:
    intercept:
      active: false
  access:
    intercept:
      active: false

ds:
  login:
    intercept:
      dsactive: true
  access:
    intercept:
      dsactive: false
    check:
      #      url: http://ds-task-test.ushareit.org/ds/check/newaccess?requestPath={0}
      url: http://localhost:8088/ds/check/newaccess?requestPath={0}
  cloud:
    intercept:
      dsactive: true

remote:
  access:
    verify:
      url: https://zeus-api-test.ushareit.org/zeus/accessAuth?uri={uri}&systemCode={systemCode}
  identity:
    verify:
      url: https://zeus-api-test.ushareit.org/zeus/remote/user/info?systemCode=${system.code}
  system:
    menu:
      url: https://zeus-api-test.ushareit.org/zeus/system/menu?sysCode=${system.code}
    logout:
      url: https://zeus-api-test.ushareit.org/zeus/logout
    userinfo:
      url: https://zeus-api-test.ushareit.org/zeus/user

oidc:
  server.code: dsTaskApi
  identity.url: "https://sentry-test.ushareit.me/dex/keys"

#pipeline:
#  host: http://ds-pipeline-test.ushareit.org

sla:
  host: https://sla-service-test.ushareit.org

lakeCat:
  host: http://catalog-server
  token: rO0ABXNyADJpby5sYWtlY2F0LmNhdGFsb2cuYXV0aGVudGljYXRpb24ubW9kZWwuTG9jYWxUb2tlbjcmbiYxJvNvAgADTAAJYWNjb3VudElkdAASTGphdmEvbGFuZy9TdHJpbmc7TAAGcGFzc3dkcQB+AAFMAAZ1c2VySWRxAH4AAXhwdAANWmhlSmlhbmdEYVh1ZXQAA2JkcHEAfgAE
