-- 插入菜单信息
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (10, 'access_manager', '权限管理', '1', -1, '权限管理', '/jurisdiction', 'admin', 'admin', '0', 4);

INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (110000, 'admin_manager', '管理员管理', '2', 10, '管理员管理', '/admin/manager', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (110001, 'super_admin_manager', '超级管理员管理', '2', 10, '超级管理员管理', '/superadmin/manager', 'admin', 'admin', '0', 4);


INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (11, 'tenant_manager', '租户管理', '2', 10, '租户管理', '/jurisdiction/tenant', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (19, 'user_manager', '用户管理', '2', 10, 'ds用户管理', '/jurisdiction/user', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (25, 'role_manager', '角色管理', '2', 10, '角色管理', '/jurisdiction/role', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (34, 'menu_manager', '菜单管理', '2', 10, '菜单管理', '/jurisdiction/menu', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1579, 'task-manager', '任务管理', '1', -1, '任务管理', '/task', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1580, 'dataset-manager', '数据集管理', '1', -1, '数据集管理', '/dataset', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1581, 'dic-manager', '字典管理', '1', -1, '字典管理', '/dict', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1582, 'config-manager', '配置管理', '1', -1, '配置管理', '/config', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1583, 'task_list', '任务列表', '2', 1579, '任务列表', '/task/list', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1584, 'task_create_step1', '创建任务步骤1', '2', 1579, '创建任务步骤1', '/task/step1', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1585, 'task_step2_flink_jar', '创建任务步骤2FlinkJar', '2', 1579, '创建任务步骤2FlinkJar', '/task/step2FlinkJar', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1586, 'task_step3', '创建任务步骤3', '2', 1579, '创建任务步骤3', '/task/step3', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1587, 'task_detail', '任务详情', '2', 1579, '任务详情', '/task/detail', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1588, 'data_set_list', '数据集列表', '2', 1580, '数据集列表', '/dataset/list', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1589, 'data_set_step1', '创建数据集步骤1', '2', 1580, '创建数据集步骤1', '/dataset/step1', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1590, 'data_set_step2', '创建数据集步骤2', '2', 1580, '创建数据集步骤2', '/dataset/step2', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1591, 'data_set_step3', '创建数据集步骤3', '2', 1580, '创建数据集步骤3', '/dataset/step3', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1592, 'data_set_detail', '数据集详情', '2', 1580, '数据集详情', '/dataset/detail', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1593, 'dictionary_list', '字典列表', '2', 1581, '字典列表', '/dict/list', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1594, 'data_source_list', '数据源列表', '2', 1582, '数据源列表', '/config/datasource', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1595, 'artifact', '工件', '2', 1582, '工件', '/config/artifact', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1596, 'cluster', '集群', '2', 1582, '集群', '/config/cluster', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1597, 'cluster_detail', '集群详情', '2', 1582, '集群详情', '/config/cluster/detail', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1598, 'task_step2_flink_sql', '创建任务步骤2FlinkSQL', '2', 1579, '创建任务步骤2FlinkSQL', '/task/step2FlinkSQL', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1599, 'artifact-detail', '工件详情', '2', 1582, '工件详情', '/config/artifact/detail', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1600, 'artifact-version', '工件版本', '2', 1582, '工件版本页', '/config/artifact/version', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1601, 'task_step2_hive_cross_cloud', '创建任务步骤2HiveCrossCloud', '2', 1579, '创建任务步骤2HiveCrossCloud', '/task/step2HCCloud', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1602, 'task_step2_share_store', '创建任务步骤2ShareStore', '2', 1579, '创建任务步骤2ShareStore', '/task/step2ShareStore', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1603, 'task_step2_hive', '创建任务步骤2Hive', '2', 1579, '创建任务步骤2Hive', '/task/step2Hive', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1604, 'task_step2_spark_jar', '创建任务步骤2SparkJar', '2', 1579, '创建任务步骤2SparkJar', '/task/step2SparkJar', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1605, 'task_info', '实时任务详情', '2', 1579, '实时任务详情', '/task/info', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1606, 'task_step2_metis', '创建任务步骤2Metis2Iceberg', '2', 1579, '创建任务步骤2Metis2Iceberg', '/task/step2Metis', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1607, 'task_step2_mysql', '创建任务步骤2 Hive2MySql', '2', 1579, '创建任务步骤2 Hive2MySql', '/task/step2MySql', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1608, 'task_step2_click_house', '创建任务步骤2 Hive2ClickHouse', '2', 1579, '创建任务步骤2 Hive2ClickHouse', '/task/step2ClickHouse', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1609, 'task_step2_hive_sql', '创建任务步骤2 Hive2HiveSql', '2', 1579, '创建任务步骤2 Hive2HiveSql', '/task/step2HiveSQL', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1622, 'task_step3_hive', '创建任务步骤3hive', '2', 1579, '创建任务步骤3hive', '/task/step3Hive', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1670, 'audit', '审计', '2', 1582, '审计', '/config/audit', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1673, 'task_step2_cdc', '创建任务步骤2 CDC2Iceberg', '2', 1579, '创建任务步骤2 CDC2Iceberg', '/task/step2CDC', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1863, 'admin-manager', '管理员管理', '1', -1, '管理员管理', '/admin', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1938, 'feedback_list', '反馈列表', '2', 1863, '反馈列表', '/admin/feedback', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1962, 'task_step2_kafka', '创建任务步骤2 Kafka2ClickHouse', '2', 1579, '创建任务步骤2 Kafka2ClickHouse', '/task/step2Kafka', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1977, 'lakecat-manegement', '数据管理', '1', -1, '数据管理', '/lakecat', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1978, 'metadata', '元数据', '2', 1977, '元数据', '/lakecat/metadata', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1979, 'metadata_detail', '元数据详情', '2', 1977, '元数据详情', '/metadata/detail', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1980, 'metadata_step', '创建元数据', '2', 1977, '创建元数据', '/lakecat/meta-step', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1981, 'monitor-manager', '监控管理', '1', -1, '监控管理', '/monitor', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1982, 'monitor_pan', '监控大盘', '2', 1981, '监控大盘', '/monitor/pan', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1983, 'monitor_list', '监控列表', '2', 1981, '监控列表', '/monitor/monlist', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1984, 'config_info', '配置详情', '2', 1981, '配置详情', '/monitor/info', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (1985, 'monitor_detail', '监控详情', '2', 1981, '监控详情', '/monitor/detail', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2095, 'data-analysis', '数据分析', '1', -1, '数据分析', '/data-analysis', 'admin', 'admin', '0', 2);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2096, 'data-query', '数据查询', '2', 2095, '数据查询', '/data-analysis/query', 'admin', 'admin', '0', 2);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2106, 'engine-config', '引擎配置', '2', 2095, '引擎配置', '/data-analysis/engine', 'admin', 'admin', '0', 2);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2107, 'user-manager', '用户管理', '1', -1, '用户信息管理', '/user', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2108, 'DingDingDepList', '钉钉部门列表获取', '2', 2107, '钉钉部门列表获取', '/user/getDingDingDepList', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2109, 'DingDingDep', '钉钉部门信息获取', '2', 2107, '钉钉部门信息获取', '/user/getDingDingDep', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2110, 'EffectiveCostList', '获取有效成本部门列表', '2', 2107, '获取有效成本部门列表', '/user/getEffectiveCostList', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2117, 'bi-manager', 'BI管理', '1', -1, 'BI管理', 'external-link', 'admin', 'admin', '0', 7);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2118, 'bi-model', '业务BI', '2', 2117, '业务BI', 'https://bi-dev.ushareit.org/', 'admin', 'admin', '0', 7);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2129, 'order_list', '工单列表', '2', 1863, '工单列表', '/admin/order/list', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2130, 'order_create', '新建工单', '2', 1863, '新建工单', '/admin/order/create', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2131, 'task_step2_shell', '创建任务步骤2 Shell/Python脚本', '2', 1579, '创建任务步骤2 Shell/Python脚本', '/task/step2Shell', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2132, 'task_step2_DB', '创建任务步骤2 流式DB2Hive', '2', 1579, '创建任务步骤2 流式DB2Hive', '/task/step2DB', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2133, 'task_step2_Hudi', '创建任务步骤2 批量DB2Hive模板', '2', 1579, '创建任务步骤2 批量DB2Hive模板', '/task/step2Hudi', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2168, 'task_step2_Redis', '创建任务步骤2 Hive2Redis模板', '2', 1579, '创建任务步骤2 Hive2Redis模板', '/task/step2Redis', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2170, 'task_step2_Redshift', '创建任务步骤2 Hive2Redshift模板', '2', 1579, '创建任务步骤2 Hive2Redshift模板', '/task/step2Redshift', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2171, 'jupyterhub', 'jupyterhub 模块', '2', 1579, 'jupyterhub 模块', 'https://jupyterhub-sg-test.ushareit.org/', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2203, 'dqc', '监控中心', '1', -1, '监控中心', '/dqc/list', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2228, 'lakecat_default', '数据管理默认路由', '2', 1977, '数据管理默认路由', '/lakecat/*', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2233, 'calculate', '计算治理', '2', 1977, '计算治理', '/lakecat/calculate', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2234, 'calculate-business', '计算治理业务工作台', '2', 1977, '计算治理业务工作台', '/lakecat/calculte-business', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2235, 'calculate-platform', '计算治理平台工作台', '2', 1977, '计算治理平台工作台', '/lakecat/calculate-paltform', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2236, 'dateTransform', '日期转换', '2', 1579, '转换旧的airflow参数为新的参数', '/task/dateTransform', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2237, 'Jurisdiction-dataRole', '数据角色管理', '2', 10, '数据角色管理', '/jurisdiction/dataRole', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2238, 'cost-center', '成本中心', '2', 1863, '成本中心', '/admin/cost', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2239, 'cost-bill', '成本账单', '2', 1863, '成本账单', '/admin/cost/bill', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2240, 'cost-monitor', '成本监控', '2', 1863, '成本监控', '/admin/cost/monitor', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2243, 'dqc', ' DQC监控', '2', 10, ' DQC监控', '/dqc/list', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2244, 'dqcList', 'DQC监控列表', '2', 2203, 'DQC监控列表', '/dqc/list', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2245, 'dqcConfig', 'DQC配置', '2', 2203, 'DQC配置', '/dqc/config', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2246, 'group-manager', 'group管理', '2', 10, 'group管理', '/jurisdiction/group', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2260, 'cost-monitor-detail', '成本监控详情', '2', 1863, '成本监控详情', '/admin/cost/monitor/detail', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2268, 'workflow', '工作流管理', '2', 1579, '工作流管理', '/workflow', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2272, 'workflow_add_page', '新建工作流页面', '2', 1579, '新建工作流页面', 'https://datastudio-test.ushareit.org/workflow/add', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2273, 'workflow', '工作流', '1', -1, '工作流', '/workflow', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2274, 'workflow_detail', '工作流详情', '2', 2273, '工作流详情', '/workflow/detail', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2275, 'workflow_add', '新增工作流', '2', 2273, '新增工作流', '/workflow/add', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2276, 'workflow_edit', '编辑工作流', '2', 2273, '编辑工作流', '/workflow/edit/:id', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2277, 'workflow_manager', '工作流管理', '2', 2273, '工作流管理', '/workflow', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2288, 'task_step2_filemerge', '创建任务步骤2 小文件合并模板', '2', 1579, '创建任务步骤2 小文件合并模板', '/task/step2FileMerge', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2292, 'engine-config', '引擎配置', '2', 1582, '引擎配置', '/config/engine', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2295, 'dqcList', 'DQC监控列表', '2', 1981, 'DQC监控列表', '/monitor/dqclist', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2296, 'dqcConfig', 'DQC配置', '2', 1981, 'DQC配置', '/monitor/config', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2297, 'dqcRuleList', '规则模板列表', '2', 1981, '规则模板列表', '/monitor/ruleList', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2298, 'dqcRuleModel', '规则模板配置', '2', 1981, '规则模板配置', '/monitor/ruleModel', 'admin', 'admin', '0', 6);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2301, 'Workflow', '工作流管理', '2', 1579, '工作流管理', '/task/workflow', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2303, 'storage', '存储治理', '2', 1977, '存储治理', '/lakecat/storage', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2304, 'storage-platform', '存储治理平台工作台', '2', 1977, '存储治理平台工作台', '/lakecat/storage-paltform', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2305, 'bucket-detail', '存储治理桶存储详情', '2', 1977, '存储治理桶存储详情', '/lakecat/bucket-detail', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2311, 'connector_list', '数据源连接器', '2', 1582, '数据源连接器', '/config/connector', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2312, 'sourceInstance', '数据源实例', '2', 1582, '数据源实例', '/config/sourceInstance', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2313, 'sourceDetail', '新建数据源实例', '2', 1582, '新建数据源实例', '/config/sourceInstance/sourceDetail', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2346, 'announcement', '公告', '2', 1582, '公告', '/config/announcement', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2347, 'task_step2_file', '创建任务步骤2 Hive2File', '2', 1579, '创建任务步骤2 Hive2File', '/task/step2Hive2File', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2355, 'home-mana', '首页管理', '2', 2372, '首页管理', '/home', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2356, 'announcement-manager', '公告管理', '2', 2354, '公告管理', '/announcement', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2371, 'task_step2_training_model', '任务步骤2 模型训练', '2', 1579, '模型训练', '/task/step2TrainingModel', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2372, 'dashboard', '概览页', '1', -1, '概览页', '/', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2381, 'gettasks', '获取任务名称根据任务id和名称以及数据集', '1', -1, '获取任务名称根据任务id和名称以及数据集', '/task/getTasks', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2382, '删除任务', '删除任务', '1', -1, '删除任务', '/task/new/delete', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2391, 'chart-management', '图表管理', '2', 2095, '图表管理', '/data-analysis/chartManagement', 'admin', 'admin', '0', 2);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2392, 'dashboard-management', '仪表盘管理', '2', 2095, '仪表盘管理', '/data-analysis/dashboardManagement', 'admin', 'admin', '0', 2);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2393, 'task_check_success_path', '校验success文件格式', '2', 1579, '校验success文件格式', '/task/checkPath', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2405, 'login', 'datacake-cloud 登录', '1', -1, 'datacake-cloud 登录', '/login', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2406, 'retrieve-password', 'datacake 找回密码', '1', -1, 'datacake 找回密码', '/retrieve-password/:id', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2407, 'guidance', 'datacake-cloud 模式选择', '1', -1, 'datacake-cloud 模式选择', '/guidance', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2408, 'MFAVerify', 'datacake-cloud MFA 验证', '1', -1, 'datacake-cloud MFA 验证', '/mfa', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2415, 'cloud', '云资源注册', '2', 1582, '云资源注册', '/config/cloud', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2416, 'import-data', '数据挂载', '2', 1582, '数据挂载', '/config/import', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2442, 'assets', '资产盘点', '2', 1977, '资产盘点', '/lakecat/assets', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2443, 'assets-analysis', ' 资产分析', '2', 1977, '资产分析', '/lakecat/assets-analysis', 'admin', 'admin', '0', 3);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2444, 'meta', '元数据', '1', -1, '元数据', '/meta', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2445, 'meta-list', '元数据列表', '2', 2444, '元数据列表', '/meta/list', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2446, 'meta-detail', '元数据详情', '2', 2444, '元数据详情', '/meta/detail', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2447, 'meta-step', '元数据建表', '2', 2444, '元数据建表', '/meta/step', 'admin', 'admin', '0', 4);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2448, 'newcost-center', '新成本中心', '2', 1863, '新成本中心', '/admin/newcost', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2449, 'newcost-analysis', '成本分析', '2', 1863, '成本分析', '/admin/newcost/analysis', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2450, '/admin/newcost/analysis', '成本账单', '2', 1863, '成本账单', '/admin/newcost/bill', 'admin', 'admin', '0', 1);
INSERT INTO ds_task_${tenantName}.access_menu(id, code, name, level, parent_menu_id, description, url, CREATE_BY, UPDATE_BY, valid, product_id) VALUES (2451, 'newcost-report', '报告管理', '2', 1863, '报告管理', '/admin/newcost/report', 'admin', 'admin', '0', 1);


INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'10','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'11','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'19','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'25','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'34','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1579','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1580','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1581','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1582','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1583','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1584','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1585','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1586','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1587','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1588','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1589','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1590','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1591','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1592','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1593','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1594','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1595','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1596','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1596','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1597','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1598','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1599','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1600','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1601','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1602','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1603','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1604','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1605','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1606','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1607','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1608','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1609','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1622','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1670','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1673','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1863','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1938','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1962','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1977','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1978','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1979','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1980','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1981','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1982','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1983','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1984','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'1985','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2095','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2096','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2106','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2107','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2108','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2109','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2110','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2117','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2118','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2129','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2130','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2131','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2132','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2133','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2168','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2170','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2171','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2203','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2228','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2233','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2234','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2235','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2236','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2237','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2238','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2239','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2240','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2243','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2244','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2245','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2246','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2260','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2268','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2272','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2273','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2274','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2275','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2276','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2277','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2288','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2292','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2295','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2296','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2297','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2298','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2301','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2303','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2304','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2305','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2311','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2312','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2313','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2346','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2347','admin','admin');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2355','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2356','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2371','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2372','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2381','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2382','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2391','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2392','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2393','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2405','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2406','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2407','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2408','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2415','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2416','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2442','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2443','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2444','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2445','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2446','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2447','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2448','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2449','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2450','admin','admin');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (1,'2451','admin','admin');


INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'10','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'11','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'19','common','common');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1579','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1580','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1581','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1582','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1583','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1584','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1585','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1586','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1587','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1588','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1589','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1590','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1591','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1592','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1593','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1594','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1595','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1596','common','common');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1598','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1599','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1600','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1601','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1602','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1603','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1604','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1605','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1606','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1607','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1608','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1609','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1622','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1670','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1673','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1863','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1938','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1962','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1977','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1978','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1979','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1980','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1981','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1982','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1983','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1984','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'1985','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2095','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2096','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2106','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2107','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2108','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2109','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2110','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2117','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2118','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2129','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2130','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2131','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2132','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2133','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2168','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2170','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2171','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2203','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2228','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2233','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2234','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2235','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2236','common','common');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2238','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2239','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2240','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2243','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2244','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2245','common','common');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2260','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2268','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2272','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2273','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2274','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2275','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2276','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2277','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2288','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2292','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2295','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2296','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2297','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2298','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2301','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2303','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2304','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2305','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2311','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2312','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2313','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2346','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2347','common','common');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2355','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2356','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2371','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2372','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2381','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2382','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2391','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2392','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2393','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2405','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2406','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2407','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2408','common','common');

INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2442','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2443','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2444','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2445','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2446','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2447','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2448','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2449','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2450','common','common');
INSERT INTO ds_task_${tenantName}.access_role_menu (role_id,menu_id,CREATE_BY,UPDATE_BY) VALUES (5,'2451','common','common');

