apiVersion: batch/v1
kind: Job
metadata:
  # flink-jobmanager-wuyan
  name: ${flink_jm_name}
spec:
#  parallelism: 2 # Set the value to greater than 1 to start standby JobManagers
  template:
    metadata:
      annotations:
        prometheus.io/port: '10106'
        prometheus.io/scrape: 'true'
        iam.shareit.me/aws: ${awsIam}
        iam.shareit.me/huawei: ${huaweiIam}
        iam.shareit.me/type: env
      labels:
        app: ${jm_tm_label_name}
        component: jobmanager
        owner: ${jm_tm_label_owner}
        template: ${jm_tm_label_template}
        id: ${jm_tm_label_id}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: jobmanager
          image: ${flink_image}
          imagePullPolicy: Always
          command: ["/App/flink/bin/standalone-job.sh"]
          args: [${jm_args}]
          env:
            - name: env
              value: ${env}
            - name: region
              value: ${region}
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob-server
            - containerPort: 8081
              name: webui
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: ${flink_config_volume}
              mountPath: /opt/flink/conf
          securityContext:
            runAsUser: 0  # refers to user _flink_ from official flink image, change if necessary
      imagePullSecrets:
        - name: default-secret${nodeSelector_tolerations}
      serviceAccountName: jobmanager    ## 鉴权必须要加
      volumes:
        - name: ${flink_config_volume}   ## flink-config-volume
          configMap:
            name: ${flink_config_name}  ## flink-config-wuyan
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j.properties
                path: log4j.properties