apiVersion: v1
kind: ConfigMap
metadata:
  name: ${flink_config_name}
  labels:
    app: ${jm_tm_label_name}
  ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: ${flink_jm_name}
      uid: ${UID}
data:
  flink-conf.yaml: |+
    #  需要修改成变量
    jobmanager.rpc.address: ${flink_jm_name}
    env.log.dir: /data/logs
    taskmanager.numberOfTaskSlots: 1
    blob.server.port: 6124
    blob.storage.directory: /data/flink-data/blob
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    #  需要修改成变量
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    # restart-strategy: fixeddelay
    # restart-strategy.fixed-delay.attempts: 100000
    state.backend: rocksdb
    state.checkpoints.num-retained: 2
    state.backend.incremental: true
    state.backend.rocksdb.localdir: /data/flink-data/backend/rocksdb
    state.backend.rocksdb.ttl.compaction.filter.enabled: true
    state.backend.local-recovery: true
    taskmanager.state.local.root-dirs: /data/flink-data/backend
    state.backend.rocksdb.timer-service.factory: ROCKSDB
    # state.checkpoints.dir: obs://cbs-flink-sg/main-sg2-prod/checkpoint
    # state.savepoints.dir: obs://cbs-flink-sg/main-sg2-prod/savepoint
    state.checkpoints.dir: ${checkpoint_dir}
    state.savepoints.dir: ${savepoint_dir}
    fs.obs.security.provider: org.apache.flink.fs.obs.shaded.com.obs.services.EnvironmentVariableObsCredentialsProvider
    fs.obs.endpoint: obs.ap-southeast-3.myhuaweicloud.com
    #  需要修改成变量
    # InitContainer.dependJars: https://cbs-flink-sg.obs.ap-southeast-3.myhuaweicloud.com/hebe/test/jars/03ce7665d5d443699bb97ff8c110ba9c/reactive-mode-demo-jobs-1.0-SNAPSHOT.jar
    InitContainer.dependJars: ${initContainer_dependJars}
    Flink.execution.packages: ${flink_execution_packages}
    # $internal.pipeline.job-id: ${job_id}
    kubernetes.jobmanager.node-selector: ${node_selector}
    kubernetes.taskmanager.node-selector: ${node_selector}
    kubernetes.jobmanager.tolerations: ${tolerations}
    kubernetes.taskmanager.tolerations: ${tolerations}
    scheduler-mode: reactive
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.port: 10106
    kubernetes.jobmanager.annotations: prometheus.io/port:10106,prometheus.io/scrape:true
    kubernetes.taskmanager.annotations: prometheus.io/port:10106,prometheus.io/scrape:true
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    rest.flamegraph.enabled: true
    fs.obs.security.provider: org.apache.flink.fs.obs.shaded.com.obs.services.EnvironmentVariableObsCredentialsProvider
    fs.obs.endpoint: obs.ap-southeast-3.myhuaweicloud.com
    fs.s3.security.provider: com.amazonaws.auth.EnvironmentVariableCredentialsProvider
    AWS_REGION: ap-southeast-1
    #  需要修改成变量
    kubernetes.cluster-id: ${flink_ha_cluster_name}
    kubernetes.namespace: ${namespace}
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    # high-availability.storageDir: s3a://cbs.flink.ap-southeast-1/ads-sg1-prod/ha
    high-availability.storageDir: ${ha_storage_dir}