apiVersion: v1
kind: Service
metadata:
  ## flink-jobmanager-rest-wuyan
  name: ${flink_jm_rest_service_name}
  annotations:
    ushareit.me/svc-gen-httpproxy: flink
  ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: ${flink_jm_name}
      uid: ${UID}
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: ${jm_tm_label_name}
    component: jobmanager