apiVersion: v1
kind: Service
metadata:
  name: ${flink_jm_name}
  ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: ${flink_jm_name}
      uid: ${UID}
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: ${jm_tm_label_name}
    component: jobmanager
